spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/txmlw/ver
          label: master
          search-paths: config-repo
          username:
          password:

server:
  port: 9006
